alias shutdown='sudo shutdown -h now'
alias ls='ls --classify --color=auto --human-readable'
alias ll='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias less='less --quiet'
alias h='cd ~'
alias grep='grep --color=auto'
alias dmesg='dmesg -H'
alias qq='exit'
alias df='df --human-readable'
alias su='su -l'
alias paclog='tail -n 40 /var/log/pacman.log'
alias kill='tmux kill-session -t'
alias x='startx'
alias c='clear'
alias cleansys='sudo pacman -Rscn $(pacman -Qdtq)'
alias pacup='sudo sh /home/bcclsn/.script/btrfs_snap.sh && sudo pacman -Syu && /usr/bin/bash /home/bcclsn/.script/aur_update.sh'
alias snapshot='sudo sh /home/bcclsn/.script/btrfs_snap.sh'
alias mat='xhost + && sudo sh /usr/src/MATLAB/R2018a/bin/activate_matlab.sh && exit'
