alias shutdown='sudo shutdown -h now'
alias ll='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias less='less --quiet'
alias h='cd ~'
alias x='startx'
alias grep='grep --color=auto'
alias dmesg='dmesg -H'
alias qq='exit'
alias df='df -h'
alias su='su -l'
alias kill='tmux kill-session -t'
alias pacup='pacman -Syu'
alias cleansys='sudo pacman -Rscn $(pacman -Qdtq)'
alias pacaur='sudo timeshift-btrfs --backup-now && pacaur -Syu'
alias bcclsn='ssh -p 22 odroid@bcclsn.ddns.net'
